language: r
cache: packages
pandoc_version: 1.19.2.1

branches:
    only:
        - master

cache:
    packages: yes

before_script:
  - chmod +x ./_build.sh
    #  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
    #  - ./_deploy.sh

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    target_branch: master
